name: Kodi Addon-Check

on: [push]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest

    name: Kodi addon checker
    steps:
    - uses: actions/checkout@v2
    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@master
      with:
        kodi-version: matrix
